//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saman.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        public string Id { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ValidDateFrom { get; set; }
        public System.DateTime ValidDateEnd { get; set; }
        public string IssuedTo { get; set; }
        public string PersonId { get; set; }
        public string Reason { get; set; }
        public string Text { get; set; }
        public byte Number { get; set; }
        public int Type { get; set; }
    }
}
