//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saman.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Madraks
    {
        public int Id { get; set; }
        public string PersonId { get; set; }
        public int MadrakId { get; set; }
        public string Date { get; set; }
    
        public virtual Mardrak Mardrak { get; set; }
        public virtual Person Person { get; set; }
    }
}
