//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saman.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.HealthInsurances = new HashSet<HealthInsurance>();
            this.Jobs = new HashSet<Job>();
            this.Payments = new HashSet<Payment>();
            this.Person_Madraks = new HashSet<Person_Madraks>();
            this.Prescriptions = new HashSet<Prescription>();
            this.Retirees = new HashSet<Retiree>();
        }
    
        public string Name { get; set; }
        public string LName { get; set; }
        public string PesonalCode { get; set; }
        public string IdentityNo { get; set; }
        public string SodurPlace { get; set; }
        public string BirthYear { get; set; }
        public string BirthMonth { get; set; }
        public string BirthDay { get; set; }
        public string CodeMelli { get; set; }
        public string Tel { get; set; }
        public string Jens { get; set; }
        public string FatherName { get; set; }
        public string BSKind { get; set; }
        public string Nesbat { get; set; }
        public string TakafolKind { get; set; }
        public string ShebaAcc { get; set; }
        public string DeathDate { get; set; }
        public string ParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthInsurance> HealthInsurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_Madraks> Person_Madraks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Retiree> Retirees { get; set; }
    }
}
