//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saman.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int City { get; set; }
        public string Responsible { get; set; }
        public Nullable<int> Address { get; set; }
    }
}
