//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saman.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public long Price { get; set; }
        public long Payable { get; set; }
        public string SentDate { get; set; }
        public Nullable<short> Period { get; set; }
        public int TreatmentTypeId { get; set; }
        public string PersonId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual TreatmentType TreatmentType { get; set; }
    }
}
